[project]
name = "tienda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Erick Tucto", email = "erick@ericktucto.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
tienda = "tienda:main"

[build-system]
requires = ["uv_build>=0.13.0,<0.14.0"]
build-backend = "uv_build"
